apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-external-service
  name: prometheus-external-service
  namespace: app
spec:
  externalName: prometheus-operator-kube-p-prometheus.monitoring.svc.cluster.local
  selector:
    app: prometheus-external-service
  type: ExternalName
status:
  loadBalancer: {}